import { useState } from 'react';
import { useTranslation } from 'react-i18next';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { api } from './api';
import { errorKey } from './main';
import { Modal, Portrait, Loading } from './ui';
export function Admin({ notice }: {
    notice: (s: string) => void;
}) { const { t } = useTranslation(); const qc = useQueryClient(); const [kind, setKind] = useState('users'), [search, setSearch] = useState(''), [cursor, setCursor] = useState(''), [selected, setSelected] = useState<any>(null), [draft, setDraft] = useState<any>({}), [preview, setPreview] = useState(''); const overview = useQuery({ queryKey: ['admin-overview'], queryFn: () => api('admin/overview') }); const q = useQuery({ queryKey: ['admin', kind, search, cursor], queryFn: () => api<any[]>(`admin/${kind}?q=${encodeURIComponent(search)}&cursor=${cursor}`) }); async function update(id: string, data: unknown, target = kind) { try {
    await api(`admin/${target}/${id}`, 'PUT', data);
    setSelected(null);
    await qc.invalidateQueries({ queryKey: ['admin'] });
    await qc.invalidateQueries({ queryKey: ['admin-overview'] });
    notice(t('saved'));
}
catch (e) {
    notice(t(errorKey(e)));
} } function edit(row: any) { setSelected(row); setDraft(kind === 'plans' ? { stars: row.stars, days: row.days, active: row.active } : kind === 'policies' ? { dailyStarts: row.dailyStarts, seeLikes: row.seeLikes } : kind === 'reports' ? { status: row.status, adminNote: row.adminNote } : { value: row.value }); } return <section className="admin-page"><h1>{t('admin')}</h1><div className="stats">{Object.entries(overview.data || {}).map(([k, v]) => <div key={k}><strong>{String(v)}</strong><small>{t(k)}</small></div>)}</div><div className="admin-tabs">{['users', 'reports', 'photos', 'payments', 'plans', 'policies', 'content', 'audit'].map(k => <button key={k} className={kind === k ? 'selected' : ''} onClick={() => { setKind(k); setCursor(''); }}>{t(k)}</button>)}</div>{kind === 'users' && <label>{t('search')}<input value={search} onChange={e => { setSearch(e.target.value); setCursor(''); }}/></label>}{q.isLoading ? <Loading /> : q.error ? <p>{t('error')}</p> : !q.data?.length ? <p>{t('noRecords')}</p> : q.data.map((r: any) => <article className="admin-record" key={r.id || r.gender || r.key}><h3>{r.firstName || r.planId || r.gender || r.key || r.reason || r.action || r.purpose}</h3><small dir="ltr">{r.telegramId || r.id || ''}</small>{r.status && <p>{t('status')}: {t(r.status)}</p>}{r.stars && <p>★ {r.stars} · {r.days} {t('days')}</p>}{r.note && <p>{r.note}</p>}{kind === 'users' ? <div className="row"><button className="secondary" onClick={() => void update(r.id, { banned: !r.banned })}>{t(r.banned ? 'unban' : 'ban')}</button><button className="text-button danger" onClick={() => { if (confirm(t('deleteWarning')))
    void update(r.id, {}, 'delete'); }}>{t('deleteAccount')}</button></div> : kind === 'photos' ? <div className="row"><button className="text-button" onClick={() => void api(`admin/photo/${r.id}`).then(p => setPreview(p.url)).catch(e => notice(t(errorKey(e))))}>{t('view')}</button><button className="secondary" onClick={() => void update(r.id, { status: 'APPROVED' })}>{t('approve')}</button><button className="text-button danger" onClick={() => void update(r.id, { status: 'REJECTED' })}>{t('reject')}</button></div> : ['plans', 'policies', 'reports', 'content'].includes(kind) ? <button className="secondary" onClick={() => edit(r)}>{t('settings')}</button> : null}</article>)}{['users', 'reports', 'payments', 'photos'].includes(kind) && <div className="row"><button className="text-button" onClick={() => setCursor('')}>{t('previous')}</button>{q.data?.length === 50 && <button className="text-button" onClick={() => setCursor(q.data![49].id)}>{t('next')}</button>}</div>}{selected && <Modal title={t(kind)} onClose={() => setSelected(null)}><form onSubmit={e => { e.preventDefault(); void update(selected.id || selected.gender || selected.key, draft); }}>{Object.entries(draft).map(([k, v]) => <label key={k}>{t(({ stars: 'price', days: 'duration', value: 'content' } as Record<string, string>)[k] || k)}{typeof v === 'boolean' ? <input type="checkbox" checked={v} onChange={e => setDraft({ ...draft, [k]: e.target.checked })}/> : typeof v === 'number' ? <input type="number" value={v} required onChange={e => setDraft({ ...draft, [k]: Number(e.target.value) })}/> : k === 'status' ? <select value={String(v)} onChange={e => setDraft({ ...draft, [k]: e.target.value })}>{['OPEN', 'IN_REVIEW', 'RESOLVED', 'REJECTED'].map(s => <option key={s} value={s}>{t(s)}</option>)}</select> : <textarea value={String(v)} rows={8} onChange={e => setDraft({ ...draft, [k]: e.target.value })}/>}</label>)}<button className="primary wide">{t('save')}</button></form></Modal>}{preview && <Modal title={t('photos')} onClose={() => setPreview('')}><Portrait url={preview} alt={t('photos')}/></Modal>}</section>; }
