import 'dotenv/config';
import {PrismaClient} from '@prisma/client';
import {randomUUID} from 'node:crypto';
export async function seed(db:PrismaClient){
 if(process.env.NODE_ENV==='production')throw new Error('Seed is development-only');
 for(const [id,days,stars] of [['BASIC',7,100],['PREMIUM',30,300],['VIP',90,750]] as const)await db.plan.upsert({where:{id},create:{id,days,stars},update:{}});
 for(const [gender,dailyStarts,seeLikes] of [['MALE',3,false],['FEMALE',-1,true],['OTHER',-1,true]] as const)await db.policy.upsert({where:{gender},create:{gender,dailyStarts,seeLikes},update:{}});
 const women=['Lina','Maya','Nora','Sofia','Darya','Sara','Mina','Leila','Zara','Emma','Giulia','Aisha','Mei','Priya','Alina','Clara','Elena','Yasmin','Luna','Nadia'];const men=['Adrian','Arman','Leo','Deniz','Omar','Alex','Ravi','Luca','Daniel','Wei'];const cities=['Berlin','Istanbul','Dubai','Milan','Madrid'];const countries=['Germany','Türkiye','UAE','Italy','Spain'];const locales=['en','zh','ru','hi','ur','fa','ar','tr','es','de','it'];const users=[];
 for(let i=0;i<30;i++){const female=i<20,index=female?i:i-20,telegramId=`test-${female?'woman':'man'}-${String(index+1).padStart(2,'0')}`,name=female?women[index]:men[index];const u=await db.user.upsert({where:{telegramId},create:{telegramId,firstName:name,isTest:true,role:i===29?'ADMIN':'USER',termsAt:new Date(),termsVersion:'1.0',premiumUntil:i===21?new Date(Date.now()+30*86400000):i===22?new Date(Date.now()-86400000):null},update:{}});users.push(u);await db.profile.upsert({where:{userId:u.id},create:{userId:u.id,displayName:name,birthDate:new Date(`${1985+(i%17)}-06-15`),gender:female?'FEMALE':'MALE',interestedIn:female?['MALE']:['FEMALE'],bio:['Coffee, late-night conversations and getting lost in a new city.','A good playlist, a long walk, and someone curious.','Art galleries on Saturday. A little spontaneity every day.'][i%3],city:cities[i%5],country:countries[i%5],languages:['en',locales[(i%10)+1]],interests:[['Music','Travel','Coffee'][i%3],['Art','Cooking','Books'][i%3]],goal:['DATING','FRIENDSHIP','RELATIONSHIP'][i%3]},update:{}});await db.photo.upsert({where:{path:`seed:${female?index%3:3+index%3}:${u.id}`},create:{userId:u.id,path:`seed:${female?index%3:3+index%3}:${u.id}`,status:'APPROVED'},update:{}});}
 const man=users[20];for(let i=0;i<8;i++)await db.swipe.upsert({where:{fromId_toId:{fromId:users[i].id,toId:man.id}},create:{fromId:users[i].id,toId:man.id,kind:'LIKE'},update:{}});
 for(let i=0;i<5;i++){const woman=users[i];const [aId,bId]=[man.id,woman.id].sort();await db.swipe.upsert({where:{fromId_toId:{fromId:man.id,toId:woman.id}},create:{fromId:man.id,toId:woman.id,kind:'LIKE'},update:{}});const c=await db.conversation.upsert({where:{aId_bId:{aId,bId}},create:{aId,bId,...(i===0?{startedBy:woman.id,startedAt:new Date()}:{} )},update:{}});if(i===0&&!await db.message.count({where:{conversationId:c.id}})){await db.message.create({data:{conversationId:c.id,senderId:woman.id,body:'Hey! What’s the last place you visited that surprised you?',clientId:randomUUID()}});await db.message.create({data:{conversationId:c.id,senderId:man.id,body:'A tiny bookstore in Istanbul. I stayed for hours ☕',clientId:randomUUID()}});}}
 await db.block.upsert({where:{fromId_toId:{fromId:users[28].id,toId:users[19].id}},create:{fromId:users[28].id,toId:users[19].id},update:{}});
 if(!await db.report.findFirst({where:{fromId:users[28].id,toId:users[19].id}}))await db.report.create({data:{fromId:users[28].id,toId:users[19].id,reason:'SPAM',note:'Fictional moderation example. No real person involved.'}});
 if(!await db.paymentIntent.count({where:{userId:users[21].id}}))await db.paymentIntent.create({data:{userId:users[21].id,planId:'PREMIUM',stars:300,days:30,status:'PENDING',expiresAt:new Date(Date.now()+1800000)}});
 for(const [key,value]of Object.entries({terms:'DRAFT — operator review required. Adults 18+ only. No harassment, impersonation, scams, minors or non-consensual sexual content. Matches require mutual consent. Memberships are one-time Stars purchases, not automatic renewals. Use /paysupport for payment issues. Insert operator identity, contact, jurisdiction and refund terms before release.',privacy:'DRAFT — operator review required. We store Telegram identity, profile, photos, messages, purchases and approximate location with consent. Telegram ID and precise location are not displayed to other members. Photos use short-lived signed URLs. Deleting an account removes the profile and messages and queues photo removal; anonymized payment records remain. The operator must define backup/financial retention, data controller, processors, rights contact and cross-border safeguards before release.',safety:'Meet in public and tell someone you trust. Never send money to strangers. Never share your exact address. Block/report unsafe behavior. Telegram login is not proof of age or identity. Contact local emergency services in an emergency.'}))await db.content.upsert({where:{key},create:{key,value},update:{}});
 return {users:30,women:20,men:10,admin:'test-man-10'};
}
if(require.main===module){const db=new PrismaClient();seed(db).then(console.log).catch(e=>{console.error(e.message);process.exitCode=1;}).finally(()=>db.$disconnect());}
